# version: "3.9"

# services:

#   backend:
#     build: .
#     container_name: hostel_backend
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"

#   frontend:
#     build: ./frontend
#     container_name: hostel_frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend

services:
  backend:
    image: armanshikalgar/hostel-backend:1.0
    container_name: hostel_backend
    ports:
      - "8000:8000"

  frontend:
    image: armanshikalgar/hostel-frontend:1.0
    container_name: hostel_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend